[theme]
# Primary accent color for interactive elements.
primaryColor = "#950bbf"

# Background color for the main content area.
backgroundColor = "#262d33"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#30383b"

# Color used for almost all text.
textColor = "#e2dee3"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "Montserrat"
